### PR TITLE
feat: Activate .editorconfig rules in the project

### PR DESCRIPTION
**Pull request by dspetrov**
# Activate .editorconfig rules in the project

## Description
As a part of research and implementation of StyleCop (or similar) rules, .editorconfig rules were activated in the project.

The research involved articles, ChatGPT and checking the following open source repos:
- https://github.com/ardalis/CleanArchitecture
- https://github.com/HangfireIO/Hangfire
- https://github.com/nopSolutions/nopCommerce
- https://github.com/PiranhaCMS/piranha.core
- https://github.com/OrchardCMS/OrchardCore
- https://github.com/umbraco/Umbraco-CMS
- https://github.com/simplcommerce/SimplCommerce
- https://github.com/Squidex/squidex

Notes and conclusions:
- Most of the checked open source projects use .editorconfig
- Just a few of them use StyleCop
- Using .editorconfig is a standard approach, supported by popular IDEs (directly or through extensions)
- .editorconfig provides a good set of rules and flexibility how they are applied (auto fixing, suggestions, warnings, etc)
- There are standard Microsoft and and .NET System sets of rules that are applied by default on the project
- StyleCop provides an even larger set of rules that can be applied
- StyleCop has several ways to be configured

Our approach and possible future changes:
- Use .editorconfig as changed in this PR
- Fix all the issues coming from .editorconfig and from the standard rules that are applied at the moment
- If we consider a need of more rules after that, start with the default StyleCop rules and turn off rules that we don't consider useful by using stylecop.json configuration

Some of the used resources:
- https://github.com/DotNetAnalyzers/StyleCopAnalyzers
- https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md
- https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/documentation
- https://bytedev.medium.com/quickly-setup-stylecop-for-new-net-solutions-275fc755b69e

## Related Issues
[List any related issues (e.g., fixes #123, addresses #456).](https://github.com/endatix/endatix/issues/2)

## Type of Change
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by PeterMarinov — DISMISSED** [review]

**Comment by PeterMarinov** [comment]
@dspetrov  - I have approved, but after some research, I wanted to suggest few changes:

image

### Details

* **EnforceCodeStyleInBuild** - is disabled, by default, on build for all .NET projects - [docs here](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enforcecodestyleinbuild) 🟢 recommendation: set to **true
* **CodeAnalysisTreatWarningsAsErrors** - If you use the -warnaserror flag when you build your projects, all code analysis warnings are also treated as errors. [docs here](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-8#treat-warnings-as-errors): 🟢 recommendation: set to **true**
* **TreatWarningsAsErrors** - The TreatWarningsAsErrors option treats all warnings as errors [docs here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#treatwarningsaserrors). 🟢 recommendation: set to **true**
* **AnalysisMode** -  [docs here](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismode) if you want to enable all rules as build warnings, set the value to All. 🟢 recommendation: set to **All**
* **AnalysisLevel** - The AnalysisLevel property lets you specify a set of code analyzers to run according to a .NET release. The latest code analyzers that have been released are used. This is the default. [docs here](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysislevel). 🟢 recommendation: set to **latest**

Let me know if this is causing too much pain to clean all current warnings and I can help as part of the PR

**Comment by dspetrov** [comment]
@PeterMarinov, I agree that that this is the correct approach and I've been thinking about enforcing of the rules (no matter from editorconfig or StyleCop) at some moment.
### Current state
I've checked all the changes when applying the rules locally. They change around 200 files. Some of the changes weren't good and I made some small changes in the .editorconfig (they can be seen in a commit). I would say the rules are fine now.
The good news is that most of the problems are nothing complicated and they are totally around 600.
Not so trivial are problems with nullable / non nullable types and objects. Some of them could need some time to manage well. We have a task for this - #34
The other complication is that currently there are ongoing changes for the nuget packages.
### Proposed approach
1. I commit my changes now in .editorconfig and merge the PR
1. After we merge any ongoing changes and before starting new (so we don't have conflicts because otherwise we'll have lots) we quickly do:
   - #34
   - Run locally `dotnet format ./Endatix.sln --no-restore` and commit the changes
   - Apply the changes in all proj files as you suggest
   - Manually fix all the errors
   - This step will take some time but I believe it can be done for a few hours to a day by one person so it won't stuck other dev work

Let me know if the plan looks good for you and if you have an idea about any parts of it being enhanced. When we agree on a plan, I'll create an issue.

**Comment by PeterMarinov** [comment]
@dspetrov  - Thanks for the details. Totally agree with the plan. I have added this issue and have linked it to the PR - #66

**Comment by dspetrov** [comment]
@PeterMarinov, cool, I'll proceed

**Review by PeterMarinov — APPROVED** [review]

**Pull request merged**
